### ISSUE TITLE
Add support for new Webhooks

### ISSUE THREAD

**Issue by JoshAtticus** [3r1s-s/meo#17]
Webhooks no longer use the username: post format, instead, they use the webhook id: username: post format. The Webhook ID is included in the message so that clients can get the Webhooks PFP.

**Comment by JoshAtticus** [comment]
Was this actually completed?

**Comment by 3r1s-s** [comment]
Idk idc 👍

**Comment by 3r1s-s** [comment]
yes its been completed for real now
