### ISSUE TITLE
Wide mode settings strings are undefined in languages other than en-us

### ISSUE THREAD

**Issue by JoshAtticus** [3r1s-s/meo#28]
When using English UK or another language, the strings for wide mode in Settings --> General --> Miscellaneous are undefined.

> English UK
>
> <img width="708" alt="Screenshot 2024-06-26 at 7 13 28 pm" src="https://github.com/3r1s-s/meo/assets/72828296/c1617c7e-6c83-4e26-b580-4c83e7b9826d">

> English US
>
> <img width="711" alt="Screenshot 2024-06-26 at 7 15 06 pm" src="https://github.com/3r1s-s/meo/assets/72828296/55bee2bb-c400-4677-a722-5e01a06806e6">

**Comment by 3r1s-s** [comment]
i forgo thanks for bringing it to attention
