### ISSUE TITLE
last seen 54 years ago

### ISSUE THREAD

**Issue by Supernoodles99** [3r1s-s/meo#52]
profiles keep showing as being last active 54 years ago
![image](https://github.com/user-attachments/assets/b6d1cf5b-a13c-4362-b512-7cfb8debb883)
![image](https://github.com/user-attachments/assets/f3986188-cb75-4939-87f6-ca671c4ff8be)
![image](https://github.com/user-attachments/assets/8b4b2f9d-e6d9-43ec-84c4-708490a81f0d)

**Comment by ScratchyTAS** [comment]
![Screenshot_20240917_175032_Chrome](https://github.com/user-attachments/assets/4299ccc9-d8ef-48bc-bf1d-9da46e447ecd)

**Comment by maxymeems** [comment]
![Screenshot_20240917_175032_Chrome](https://github.com/user-attachments/assets/3e9912c0-e57d-480d-8cd7-f4d5cb3cc05f)

**Comment by 3r1s-s** [comment]
Fixeth
